version: '3.1'

services:
  chrome:
    image: selenium/standalone-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
  app:
    build:
      context: .
      dockerfile: docker/containers/app/Dockerfile

    depends_on:
      - database
    ports:
      - "35729:35729"
      - "3000:3000"
    volumes:
      - app-data:/usr/src/app
      - gem_cache:/gems
    env_file:
      - docker/containers/database/development.env
      - docker/containers/app/development.env
    command: [ "bin/rails", "s" ]

    stdin_open: true
    tty: true
    secrets:
      - host_ssh_key

  database:
    image: postgres
    env_file:
      - docker/containers/database/development.env

    volumes:
      - database-data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: docker/containers/web/Dockerfile

volumes:
  database-data:
  gem_cache:
  app-data:

secrets:
  host_ssh_key:
    file: ~/.ssh/id_rsa
